name: Build & Release

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.7.0'

      - name: Install dependencies
        run: npm ci

      - name: Generate artifacts (build)
        run: NODE_ENV=production npm run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zip/site-indicator-*.zip

      - name: Publish to Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file-path: zip/site-indicator-*.zip
          extension-id: jpipimaonfgahpepmjnhbbafgceikfal
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          glob: true
