name: PR (checks)

on:
  pull_request:
    branches:
      - '*'

jobs:
  pr-checks:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate artifacts (build)
        run: NODE_ENV=production npm run build
